#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# author:onion
# datetime:2019/12/13 10:05
# software: PyCharm

from argparse import  ArgumentParser


def createArgparser(usage):
    _server_url='_server_url'
    _proxy='_proxy'
    _devkey='_devkey'
    """ returns a parser for command line arguments """

    a_parser = ArgumentParser(description=usage)
    # optional command line parameters
    a_parser.add_argument('--server_url', default=_server_url,
                          help='TestLink Server URL of XML-RPC (default: %(default)s) ')
    a_parser.add_argument('--proxy', default=_proxy,
                          help='HTTP Proxy (default: %(default)s) ')
    # pseudo optional command line parameters,
    # must be set individual for each user
    a_parser.add_argument('--devKey', default=_devkey,
                          help='Users devKey generated by TestLink (default: %(default)s) ')
    return a_parser

if __name__ == '__main__':
    parse =createArgparser('test test')
    parse.parse_args()
#命令行使用
# base_test> python .\command_test.py --help